name: Git Push
description: |
  This action creates a new commit and pushes the changes back to the remote repository.
  It automatically commits files that were modified during the workflow run.

  ## Usage

  ```yaml
    steps:
      - name: Git Push
        uses: tmknom/git-push-action@v0
        with:
          message: add useful feature
  ```

inputs:
  message:
    required: true
    description: The commit message.

outputs:
  pushed:
    value: ${{ steps.push.outcome == 'success' && 'true' || 'false' }}
    description: Whether the changes pushed to the repository.
  branch:
    value: ${{ steps.push.outputs.branch }}
    description: Name of the pushed branch.

runs:
  using: composite

  steps:
    - name: Traceable Identifier
      id: traceable
      uses: tmknom/traceable-identifier-action@6555160c543eb771a876fb4ceaecd43ec79df7b6 # v0.1.0

    - name: Git diff status
      id: status
      run: |
        echo "::group::Git diff status"
        set -x
        if [[ "$(git status --short --untracked-files)" != "" ]]; then
          echo "diff=true" >> "${GITHUB_OUTPUT}"
        else
          echo "diff=false" >> "${GITHUB_OUTPUT}"
        fi
        echo "::endgroup::"
      shell: bash

    - name: Git push
      id: push
      if: ${{ steps.status.outputs.diff == 'true' }}
      env:
        MESSAGE: ${{ inputs.message }}
        IDENTIFIER: ${{ steps.traceable.outputs.identifier }}
      run: |
        echo "::group::Git push"
        set -x
        branch="auto/${IDENTIFIER}"
        log="Generated by ${GITHUB_WORKFLOW} workflow."
        url="- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

        git switch -c "${branch}"
        git add .
        git commit -m "${MESSAGE}" -m "${log}" -m "${url}"
        git push origin "${branch}"
        echo "branch=${branch}" >> "${GITHUB_OUTPUT}"
        echo "::endgroup::"
      shell: bash
