name: Test
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "action.yml"
      - ".github/workflows/test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  exercise:
    name: Setup and Exercise
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    outputs:
      pushed: ${{ steps.exercise.outputs.pushed }}
      branch: ${{ steps.exercise.outputs.branch }}
      pushed-file: ${{ steps.setup.outputs.file }}
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Traceable Identifier
        id: traceable
        uses: tmknom/traceable-identifier-action@6555160c543eb771a876fb4ceaecd43ec79df7b6 # v0.1.0

      - name: Setup
        id: setup
        env:
          IDENTIFIER: ${{ steps.traceable.outputs.identifier }}
        run: |
          set -x
          filename="${IDENTIFIER}.md"
          date > "${filename}"
          echo "file=${filename}" >> "${GITHUB_OUTPUT}"

      - name: Exercise
        id: exercise
        uses: ./
        with:
          message: Test git-push-action

  verify:
    name: Verify
    needs: [exercise]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1
        with:
          ref: ${{ needs.exercise.outputs.branch }}
          fetch-depth: 2

      - name: Verify
        env:
          PUSHED: ${{ needs.exercise.outputs.pushed }}
          PUSHED_FILE: ${{ needs.exercise.outputs.pushed-file }}
        run: |
          set -x
          test "${PUSHED}" = "true"
          test "$(git log -1 --pretty=%s)" = "Test git-push-action"
          test "$(git log -1 --name-only --pretty=format:)" = "${PUSHED_FILE}"

  teardown:
    name: Teardown
    if: ${{ always() }}
    needs: [exercise, verify]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Delete branch
        env:
          BRANCH: ${{ needs.exercise.outputs.branch }}
        run: |
          set -x
          git push origin "${BRANCH}" --delete || true

  test-no-pushed:
    name: Test for no pushed
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          message: Test git-push-action with no-pushed

      - name: Verify
        env:
          PUSHED: ${{ steps.exercise.outputs.pushed }}
        run: |
          set -x
          test "${PUSHED}" = "false"
